spring.application.name: jcpFE
server.port: 9004
#spring.profiles.active: auth, db-fe, ssl

# JCP Clients
localhost.public: ${HOST:${HOSTNAME:localhost}}
jcp.client.id: jcp-fe
jcp.client.secret: f379a100-46bb-4fc8-a660-947a98a3afab
#jcp.client.callback: n/a
jcp.client.ssl.private: true       #jcp.client.ssl.internal: true
jcp.client.ssl.public: true
jcp.client.auth.public: ${localhost.public}
jcp.client.auth.port: 8998
#jcp.client.apis.private: localhost
#jcp.client.apis.public: ${localhost.public}
#jcp.client.apis.port: 9001
jcp.client.jslWB.private: localhost
jcp.client.jslWB.public: ${localhost.public}
jcp.client.jslWB.port: 9003
jcp.client.fe.private: localhost
jcp.client.fe.public: ${localhost.public}
jcp.client.fe.port: 9004
