version: "3.7"
services:

  auth_josp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # KeyCloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      # DB
      DB_VENDOR: mysql
      DB_ADDR: 172.17.0.1
      DB_PORT: 8999
      DB_DATABASE: jcp_auth
      DB_USER: jcp_auth
      DB_PASSWORD: auth_jcp
      JDBC_PARAMS: 'allowPublicKeyRetrieval=true&useSSL=false'
      #KEYCLOAK_IMPORT: /import-export/import-jcp.json
      #KEYCLOAK_EXPORT: /import-export/export-all.json
      WAIT_FOR_DB: 'true'

    volumes:
      - ./import-export:/import-export
    ports:
      - 8998:8443

networks:
  default:
    external:
      name: jcp-dev