spring.application.name: jcpAll
server.port: 9000
spring.profiles.active: auth, db-all, ssl

# JCP Clients
localhost.public: ${HOST:${HOSTNAME:localhost}}
jcp.client.id: jcp-all
jcp.client.secret: 27e3d70d-5dd0-433e-a85a-40fa4b66d1ad
jcp.client.callback: https://${localhost.public}:${server.port}/apis/pub/jslwebbridge/core/user/2.0/login/code/
jcp.client.ssl.private: true
jcp.client.ssl.public: true
jcp.client.auth.public: ${localhost.public}
jcp.client.auth.port: 8998
jcp.client.apis.private: localhost
jcp.client.apis.public: ${localhost.public}
jcp.client.apis.port: 9000
jcp.client.jslWB.private: localhost
jcp.client.jslWB.public: ${localhost.public}
jcp.client.jslWB.port: 9000
jcp.client.fe.private: localhost
jcp.client.fe.public: ${localhost.public}
jcp.client.fe.port: 9000

# JCP APIs (all instance, dev)
jcp.apis.gws.cache.load_on_startup: false
jcp.apis.gws.availability.delay_seconds: 10
jcp.apis.gws.availability.attempts: 3

# JCP GWs
jcp.gws.enabled: true
jcp.gws.region: Europe
jcp.gws.o2s.ip.internal: localhost
jcp.gws.o2s.ip.public: ${localhost.public}
jcp.gws.o2s.port: 9101
jcp.gws.o2s.maxClients: 100
jcp.gws.s2o.ip.internal: localhost
jcp.gws.s2o.ip.public: ${localhost.public}
jcp.gws.s2o.port: 9102
jcp.gws.s2o.maxClients: 100

# JSL WB
jcp.jsl.remove.delay: 900
jcp.jsl.heartbeat.delay: 60

# JSL Configs
jsl.version: 2.0.0
jcp.url.apis: ${jcp.client.apis.public}:${jcp.client.apis.port}
jcp.url.auth: ${jcp.client.auth.public}:${jcp.client.auth.port}
jsl.comm.local.enabled: false
jsl.comm.local.discovery: DNSSD
