spring.application.name: jcpGWs
server.port: 9002
spring.profiles.active: auth, db-apis, ssl

# JCP Clients
localhost.public: ${HOST:${HOSTNAME:localhost}}
jcp.client.id: jcp-gws
jcp.client.secret: 4f5985ac-0e42-4f45-ae74-a859d4fd5184
#jcp.client.callback: n/a
jcp.client.ssl.private: true
jcp.client.ssl.public: true
jcp.client.auth.public: ${localhost.public}
jcp.client.auth.port: 8998
jcp.client.apis.private: localhost
jcp.client.apis.public: ${localhost.public}
jcp.client.apis.port: 9001
#jcp.client.jslWB.private: localhost
#jcp.client.jslWB.public: ${localhost.public}
#jcp.client.jslWB.port: 9003
#jcp.client.fe.private: localhost
#jcp.client.fe.public: ${localhost.public}
#jcp.client.fe.port: 9004

# JCP GWs
jcp.gws.enabled: true
jcp.gws.region: Europe
jcp.gws.o2s.ip.internal: localhost
jcp.gws.o2s.ip.public: ${localhost.public}
jcp.gws.o2s.port: 9101
jcp.gws.o2s.maxClients: 100
jcp.gws.s2o.ip.internal: localhost
jcp.gws.s2o.ip.public: ${localhost.public}
jcp.gws.s2o.port: 9103
jcp.gws.s2o.maxClients: 100