version: "3.7"
services:

  dbms_josp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "8999:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./configs:/etc/mysql/conf.d
      - ./../../../../envs/dockers/dbms/mysql/data:/var/lib/mysql

networks:
  default:
    external:
      name: jcp-dev